[book]
title = "How I Built freeCodeCamp's Calculator with Elm"
authors = ["Dwayne Crooks"]
language = "en"

[output.html]
mathjax-support = true

[output.html.code.hidelines]
css = "~"
elm = "~"
html = "~"
js = "~"
json = "~"
