[book]
title = "How I Built freeCodeCamp's Calculator with Elm"
authors = ["Dwayne Crooks"]
src = "src"
language = "en"
multilingual = false

[output.html.code.hidelines]
html = "~"
css = "~"
js = "~"

elm = "~"
